import type { NextPage } from 'next';
import Head from 'next/head';
import { NavBar } from '../components/common/navbar';

const Home: NextPage = () => {
  return (
    <div className='h-screen bg-primary-light'>
      <Head>
        <title>ResteFest</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar />

      <main className='flex flex-col gap-5 p-5 bg-white m-7'>
        <h1 className='font-semibold text-primary-dark font-heading'>
          Hva har du i kjøleskapet?
        </h1>
        <p className='text-sm font-roboto'>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
